from pathlib import Path
from datetime import datetime
from io import BytesIO
from reportlab.pdfgen import canvas
from .exceptions import ReceiptRenderError, PrinterOfflineException, StorageQuotaException

class ReceiptRenderer:
    def render(self,order): raise NotImplementedError
class ThermalEscPosRenderer(ReceiptRenderer):
    def render(self,order):
        if order.get('status')!='paid': raise ReceiptRenderError('Only paid orders can produce receipts')
        lines=[b'\x1b@', b'VINTAGE VINYL RECORD STORE\n', f"Order: {order['order_number']}\n".encode(), b'------------------------------\n']
        for x in order['lines']:
            lines.append(f"{x['title'][:24]:24} {float(x['line_total']):8.2f}\n".encode())
        lines.append(b'------------------------------\n'); lines.append(f"TOTAL {float(order['grand_total']):.2f}\n\nThank you!\n".encode()); return b''.join(lines)
class PdfReceiptRenderer(ReceiptRenderer):
    def __init__(self,storage): self.storage=Path(storage)
    def render(self,order):
        if order.get('status')!='paid': raise ReceiptRenderError('Only paid orders can produce receipts')
        now=datetime.now(); out=self.storage/now.strftime('%Y/%m/%d'); out.mkdir(parents=True,exist_ok=True)
        target=out/f"{order['order_number']}.pdf"; tmp=target.with_suffix('.tmp')
        buf=BytesIO(); c=canvas.Canvas(buf,pagesize=(260,420)); y=390
        c.setFont('Helvetica-Bold',12); c.drawString(20,y,'VINTAGE VINYL'); y-=22; c.setFont('Helvetica',9); c.drawString(20,y,order['order_number']); y-=18
        for x in order['lines']:
            c.drawString(20,y,x['title'][:28]); c.drawRightString(240,y,f"{float(x['line_total']):.2f}"); y-=15
        y-=5; c.line(20,y,240,y); y-=18; c.setFont('Helvetica-Bold',11); c.drawRightString(240,y,f"TOTAL {float(order['grand_total']):.2f}"); y-=30; c.setFont('Helvetica',8); c.drawString(20,y,'Receipt generated by Vintage Vinyl Marketplace')
        c.save(); tmp.write_bytes(buf.getvalue()); tmp.replace(target); return target.read_bytes(), str(target)
class ReceiptDispatcher:
    def __init__(self,storage): self.storage=storage; self.pdf=PdfReceiptRenderer(storage); self.thermal=ThermalEscPosRenderer()
    def render(self,order,format='thermal'):
        return self.thermal.render(order) if format=='thermal' else self.pdf.render(order)[0]
    def print(self,order):
        try:
            data,path=self.pdf.render(order); return {'format':'pdf','path':path,'bytes':len(data)}
        except OSError as e: raise StorageQuotaException('Receipt storage unavailable',{'error':str(e)})
    def email(self,order,address):
        if '@' not in (address or ''): raise ValueError('Invalid email address')
        return {'queued':True,'address':address}
    def reprint(self,order): return self.print(order)
